db_filename: review_data.db
video_dir: /mnt/EA59000358FFCBF7/ML/compressed_videos/GKNP_2025_videos_resized/Resize
db_dir: ''
species_behaviors_csv_path: /home/jonas/Documents/projects/review-app/review_app/data/species_behaviors.csv
species_csv_mode: override
species_behaviors_csv_mode: override
behavior_defaults:
- does_not_react
- reacts_to_camera
annotator_name: djonas
blank_threshold: 0.75
species_threshold: 0.75
dark_mode: true
language: en
autoplay: true
muted: false
auto_transcode: true
playback_speed: 1.0x
species_csv_path: /home/jonas/Documents/projects/review-app/review_app/data/species.csv
