# Docker specific config.
# Mount your video directory to /input_videos in docker-compose.yml
video_dir: /input_videos/

# This directory will be volume-mounted for persistence.
db_dir: /app/_local_db/
db_filename: review_data.db
recreate_db_on_start: false

# Valid species codes.
species_csv_path: /app/docs/species.csv
species_column: Nom_commun_anglais

behaviors_csv_path: /app/docs/species_behaviors.csv

# Valid behavior codes.
behavior_defaults:
  - reacts_to_camera
  - does_not_react

# Optional queue ranking CSV inside container path.
# priority_csv_path: /app/docs/annotation_priority.csv
