services:
  review-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./_local_db:/app/_local_db
      # Mount your videos here
      - /home/jonas/Documents/input_videos/:/input_videos
    environment:
      - LOCAL_CONFIG_YAML=/app/config.docker.yaml
      - REVIEW_APP_USER_EMAIL=${REVIEW_APP_USER_EMAIL:-reviewer@local}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
