services:
  review-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./_local_db:/app/_local_db
      # Mount your videos here
      #
      - /mnt/EA59000358FFCBF7/ML/compressed_videos/GKNP_2025_videos_resized/Resize/:/input_videos
    environment:
      - LOCAL_CONFIG_YAML=/app/config.docker.yaml
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
